server:
  port: ${PORT:2222}

spring:
  application:
    name: account-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.19.72.112:5432/postgres
    platform: postgres
    username: postgres
    password: mysecretpassword

---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://172.19.72.112:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver


---
spring:
  profiles: gcp
  datasource:
    url: jdbc:postgresql://35.238.60.18:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: mysecretpassword