server:
  port: ${PORT:3333}

spring:
  application:
    name: customer-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.19.72.112:5432/postgres
    platform: postgres
    username: postgres
    password: mysecretpassword

---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://172.19.72.112:5432/postgres
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver


---
spring:
  profiles: gcp
  datasource:
    url: jdbc:postgresql://google/postgres?useSSL=false&socketFactoryArg=shining-landing-195414:us-central1:postgres&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=mysecretpassword
    driver-class-name: org.postgresql.Driver
