apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-service
  labels:
    run: customer-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: customer-service
    spec:
      containers:
      - name: customer-service
        image: ashaushus/mycustomer:v8
        ports:
        - containerPort: 3333
          protocol: TCP
      - name: postgres
        image: postgres:9.6
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 5432
            protocol: TCP